### ISSUE TITLE
Error handling in the row processing function

### ISSUE THREAD

**Issue by sabelka** [dmitigr/pgfe#10]
I wonder what the correct way of error handling inside the row processing handler is.
For me it would seem quite logical to throw an exception like in the following example:
```
db.execute([&data](auto&& row) {
        auto color = to<std::string>(row["color"]);
        if (!color_name_is_valid(color))
            throw std::runtime_error("my database contain an invalid color name!");
    }, "SELECT color FROM palette");
```
But when I do this, it seems that the database connection is not cleaned up properly. When I execute the next database query I get an error saying that "another command is already in progress".

So, is throwing exeptions supported? Or is there some other ways of error handling?

**Comment by dmitigr** [comment]
Hello,

The current semantic of method `Connection::execute` assumes that throwing an exception from row handler doesn't affects the connection instance. For now, you can set some error flag and just return `false` from the row handler and call `db.process_responses([](auto&&){})` in order to discard the unprocessed to restore the connection instance. And after that (depends on the value of the flag) you can throw the exception you like.
But indeed, it probably would be better *in most cases* to complete the response and return the connection back to the ready to next query state in cases when the row handler thrown an exception. The issue (from the library user's POV) I see here, that *another* exception may be thrown upon the completion process (imagine the stored procedure which raised the exception when returning Nth row on the server side) while the exception from the row handler is still in progress. In this case the exception thrown by the server must be nested to the exception thrown from the row handler.

Anyway, I think it's reasonable to add the feature of automatic response completion if the row handler throws an exception. Thanks for opening this issue!

**Comment by sabelka** [comment]
Thank you for your answer! So I'll use an error flag inside the row handler and just skip processing any further row input when the flag flag has been set.
```
bool have_error = false;
db.execute([&data, &have_error](auto&& row) {
        if (have_error)
            return;
        auto color = to<std::string>(row["color"]);
        if (!color_name_is_valid(color))
            have_error = true;
    }, "SELECT color FROM palette");
if (have_error)
    throw std::runtime_error("my database contains an invalid color name!");
```

**Comment by dmitigr** [comment]
API semantic has been changed! By default, Pgfe now completes the responses if the row handler throws an exception. So, you can now throw exceptions from the row handlers and Pgfe will attempt to restore the connection instance (i.e. discard the unhandled rows), for example:

```c++
void foo(Connection& conn)
{
  bool is_thrown{};
  int i{};
  try {
    conn.execute([&i](auto&&)
    {
      ++i;
      throw 1;
    }, "SELECT generate_series(1,3) AS num");
  } catch (const int value) {
    is_thrown = true;
    assert(value == 1);
  }
  assert(is_thrown);
  assert(i == 1);
  assert(conn.is_ready_for_request());
}
```

Furthermore, the behavior is configurable now, for example:

```c++
void bar(Connection& conn)
{
  // Execute and process only first row
  {
    int i{};
    conn->execute<Row_processing::complete>([&i](auto&&)
    {
      ++i;
    }, "SELECT generate_series(1,3) AS num");
    assert(i == 1);
    assert(conn->is_ready_for_request());
  }
}
```

**Comment by sabelka** [comment]
Thank you Dmitry! Just pulled - works perfect!
